services:
    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: postgresql.,
            MYSQL_DATABASE: salaryman
            MYSQL_USER: salaryman
            MYSQL_PASSWORD: password.,
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - salarymannet
    php-fpm:
        build:
            context: docker/php
        depends_on:
            - db
        networks:
            - salarymannet
        volumes:
            - ./:/usr/share/nginx/html
        ports:
            - 9000:9000
    nginx:
        build:
            context: docker/nginx
        environment:
            - NGINX_HOST=salaryman.local
            - NGINX_PORT=80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/usr/share/nginx/html
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php-fpm
        networks:
            - salarymannet

networks:
    salarymannet:
